export { COOKIE_NAME, LOGIN_PATH, ONE_YEAR_MS } from "@shared/const";
import { LOGIN_PATH } from "@shared/const";

export const APP_TITLE = import.meta.env.VITE_APP_TITLE || "AutoKI Assistent";

export const APP_LOGO = "/autoki-logo.png";

/**
 * Start the login flow.
 *
 * The authorize URL is built server-side so the CSRF nonce in the OAuth `state`
 * parameter is generated by the party that also sets the cookie it is checked
 * against. A URL assembled in the browser cannot provide that guarantee.
 */
export const getLoginUrl = () => LOGIN_PATH;
